name: CD

on:
  workflow_dispatch:
  push:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux-arm:
    runs-on: ubuntu-22.04-arm

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build -r --verbose

      - name: Artifact - Linux Binary arm64
        uses: actions/upload-artifact@v4
        with:
          name: hashfolder-linux-arm64
          retention-days: 1
          path: ./target/release/hashfolder

  build-linux-x86_64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build -r --verbose

      - name: Artifact - Linux Binary x86_64
        uses: actions/upload-artifact@v4
        with:
          name: hashfolder-linux-x86_64
          retention-days: 1
          path: ./target/release/hashfolder

  build-windows-x86_64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build -r --verbose

      - name: Artifact - Windows Binary x86_64
        uses: actions/upload-artifact@v4
        with:
          name: hashfolder-windows-x86_64
          retention-days: 1
          path: .\target\release\hashfolder.exe